### PR TITLE
Follow PSR-12

### PR DESCRIPTION
**Pull request by szepeviktor**
@WampServer Follow [PSR-12](https://www.php-fig.org/psr/psr-12/) and fix a filename: `loss_func/Mean-Absolute -Error.php`

### CODE REVIEW

**Comment by WampServer** [comment]
Thank you for the pull request. I merged it.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by WampServer** [comment]
‎

**Comment by WampServer** [comment]
.

**Pull request merged**
